version: '3.8'

services:
  main-app:
    build:
      context: .
      dockerfile: Dockerfile.main
    ports:
      - "5000:5000"
      - "8000:8000"  # WebSocket port
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - MCP_SERVER_URL=http://mcp-server:5001
      - MCP_CLIENT_ID=main_app
      - MCP_CLIENT_SECRET=your_secure_secret  # Change this in production
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - EVENTLET_NO_GREENDNS=yes
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Add your OpenAI API key here
    depends_on:
      - mongodb
      - mcp-server
    volumes:
      - .:/app
    networks:
      - app-network

  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - ALLOWED_CLIENT_ID=main_app
      - ALLOWED_CLIENT_SECRET=your_secure_secret  # Change this in production
    depends_on:
      - mongodb
    volumes:
      - .:/app
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 