version: '3.8'

services:
  main-app:
    build:
      context: .
      dockerfile: Dockerfile.main
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - MCP_SERVER_URL=http://mcp-server:5001
    depends_on:
      - mongodb
      - mcp-server
    volumes:
      - .:/app
    networks:
      - app-network

  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
    depends_on:
      - mongodb
    volumes:
      - .:/app
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 