version: '3.8'

services:
  main-app:
    build:
      context: .
      dockerfile: Dockerfile.main
    ports:
      - "5001:5000"
      - "8001:8000"  # WebSocket port
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - MCP_SERVER_URL=http://mcp-server:5002
      - MCP_CLIENT_ID=renewable_energy_app
      - MCP_CLIENT_SECRET=mcp_secret_2024_renewable_energy_consultant_secure
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - EVENTLET_NO_GREENDNS=yes
      # LLM Provider Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # OpenAI API key
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}  # Optional: For Groq or Ollama
      - OPENAI_MODEL=${OPENAI_MODEL}  # Optional: Specify model
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}  # Optional: Claude API key
    depends_on:
      - mongodb
      - mcp-server
    volumes:
      - .:/app
      - vector_store:/app/data/vector_store
    networks:
      - app-network

  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    ports:
      - "5002:5002"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - ALLOWED_CLIENT_ID=renewable_energy_app
      - ALLOWED_CLIENT_SECRET=mcp_secret_2024_renewable_energy_consultant_secure
      # External Data Source API Keys
      - EIA_API_KEY=${EIA_API_KEY}
      - SOLARGIS_API_KEY=${SOLARGIS_API_KEY}
      - WINDEUROPE_API_KEY=${WINDEUROPE_API_KEY}
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - vector_store:/app/data/vector_store
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  vector_store: 